#include "Operands.h"
namespace Asm
{
	const RegOrOperandGroup Operands[] =
	{
		{ 0 },

		{ _OP(Seg_cs),	NULL },
		{ _OP(Seg_ds),	NULL },
		{ _OP(Seg_es),	NULL },
		{ _OP(Seg_fs),	NULL },
		{ _OP(Seg_gs),	NULL },
		{ _OP(Seg_ss),	NULL },

		{ _REG_EAX,		_OP(Rex) },
		{ _REG_ECX,		_OP(Rex_B) },
		{ _REG_EDX,		_OP(Rex_X) },
		{ _REG_EBX,		_OP(Rex_XB) },
		{ _REG_ESP,		_OP(Rex_R) },
		{ _REG_EBP,		_OP(Rex_RB) },
		{ _REG_ESI,		_OP(Rex_RX) },
		{ _REG_EDI,		_OP(Rex_RXB) },

		{ _REG_EAX,		_OP(Rex_W) },
		{ _REG_ECX,		_OP(Rex_WB) },
		{ _REG_EDX,		_OP(Rex_WX) },
		{ _REG_EBX,		_OP(Rex_WXB) },
		{ _REG_ESP,		_OP(Rex_WR) },
		{ _REG_EBP,		_OP(Rex_WRB) },
		{ _REG_ESI,		_OP(Rex_WRX) },
		{ _REG_EDI,		_OP(Rex_WRXB) },

		{ _REG_RAX,		_REG_R8 },
		{ _REG_RCX,		_REG_R9 },
		{ _REG_RDX,		_REG_R10 },
		{ _REG_RBX,		_REG_R11 },
		{ _REG_RSP,		_REG_R12 },
		{ _REG_RBP,		_REG_R13 },
		{ _REG_RSI,		_REG_R14 },
		{ _REG_RDI,		_REG_R15 },

		{ _REG_RAX,		_REG_EAX },
		{ _REG_RCX,		_REG_ECX },
		{ _REG_RDX,		_REG_EDX },
		{ _REG_RBX,		_REG_EBX },
		{ _REG_RSP,		_REG_ESP },
		{ _REG_RBP,		_REG_EBP },
		{ _REG_RSI,		_REG_ESI },
		{ _REG_RDI,		_REG_EDI },

		{ _REG_R8,		_REG_R8D },
		{ _REG_R9,		_REG_R9D },
		{ _REG_R10,		_REG_R10D },
		{ _REG_R11,		_REG_R11D },
		{ _REG_R12,		_REG_R12D },
		{ _REG_R13,		_REG_R13D },
		{ _REG_R14,		_REG_R14D },
		{ _REG_R15,		_REG_R15D },

		{ _REG_AL,		_REG_R8L },
		{ _REG_CL,		_REG_R9L },
		{ _REG_DL,		_REG_R10L },
		{ _REG_BL,		_REG_R11L },
		{ _REG_AH,		_REG_R12L },
		{ _REG_CH,		_REG_R13L },
		{ _REG_DH,		_REG_R14L },
		{ _REG_BH,		_REG_R15L },

		{ _OP(H_J),		_OP(L_b) },
		{ _OP(H_J),		_OP(L_z) },

		{ _OP(H_E),		_OP(L_b) },
		{ _OP(H_I),		_OP(L_b) },

		{ _OP(H_I),		_OP(L_w) },
		{ _OP(H_I),		_OP(L_z) },

		{ _OP(H_A),		_OP(L_p) },
		{ _OP(H_F),		_OP(L_v) },

		{ _OP(H_E),		_OP(L_v) },

		{ _OP(H_I),		_OP(L_v) },

		{ _OP(H_P),		_OP(L_q) },

		{ _OP(H_G),		_OP(L_b) },
		{ _OP(H_G),		_OP(L_v) },
		{ _OP(H_L),		_OP(L_b) },

		{ _OP(H_O),		_OP(L_b) },

		{ _OP(H_Q),		_OP(L_d) },
		{ _OP(H_Q),		_OP(L_q) },

		{ _OP(H_V),		_OP(L_x) },

		{ _OP(H_G),		_OP(L_y) },
		{ _OP(H_E),		_OP(L_w) },

		{ _OP(H_O),		_OP(L_v) },
		{ _OP(H_M),		_OP(L_q) },
		{ _OP(H_Y),		_OP(L_b) },
		{ _OP(H_X),		_OP(L_b) },
		{ _OP(H_X),		_OP(L_z) },
		{ _OP(H_Q),		_OP(L_pi) },
		{ _OP(H_P),		_OP(L_pi) },
		{ _OP(H_V),		_OP(L_ps) },
		{ _OP(H_W),		_OP(L_ps) },
		{ _OP(H_V),		_OP(L_pd) },
		{ _OP(H_W),		_OP(L_pd) },
		{ _OP(H_W),		_OP(L_x) },
		{ _OP(H_V),		_OP(L_q) },
		{ _OP(H_V),		_OP(L_qq) },
		{ _OP(H_H),		_OP(L_qq) },
		{ _OP(H_W),		_OP(L_qq) },
		{ _OP(H_H),		_OP(L_x) },
		{ _OP(H_H),		_OP(L_ps) },
		{ _OP(H_H),		_OP(L_pd) },
		{ _OP(H_V),		_OP(L_ss) },
		{ _OP(H_V),		_OP(L_sd) },
		{ _OP(H_W),		_OP(L_sd) },
		{ _OP(H_W),		_OP(L_ss) },
		{ _OP(H_V),		_OP(L_dq) },
		{ _OP(H_W),		_OP(L_dq) },
		{ _OP(H_M),		_OP(L_dq) },
		{ _OP(H_H),		_OP(L_dq) },
		{ _OP(H_H),		_OP(L_ss) },
		{ _OP(H_H),		_OP(L_sd) },
		{ _OP(H_H),		_OP(L_q) },
		{ _OP(H_U),		_OP(L_q) },
		{ _OP(H_E),		_OP(L_y) },
		{ _OP(H_G),		_OP(L_d) },
		{ _OP(H_M),		_OP(L_x) },
		{ _OP(H_Y),		_OP(L_v) },
		{ _OP(H_R),		_OP(L_d) },
		{ _OP(H_C),		_OP(L_d) },
		{ _OP(H_D),		_OP(L_d) },
		{ _OP(H_P),		_OP(L_d) },
		{ _OP(H_W),		_OP(L_d) },
		{ _OP(H_W),		_OP(L_q) },
		{ _OP(H_M),		_OP(L_y) },
		{ _OP(H_M),		_OP(L_p) },
		{ _OP(H_M),		_OP(L_ps) },
		{ _OP(H_M),		_OP(L_pd) },
		{ _OP(H_G),		_OP(L_w) },
		{ _OP(H_M),		_OP(L_w) },
		{ _OP(H_N),	_OP(L_q) },
		{ _OP(H_M),		_OP(L_a) },
		{ _OP(H_X),		_OP(L_v) },
		{ _OP(H_G),		_OP(L_z) },
		{ _OP(H_Y),		_OP(L_z) },
		{ _OP(H_S),		_OP(L_w) },
		{ _OP(H_U),		_OP(L_ps) },
		{ _OP(H_U),		_OP(L_pd) },
		{ _OP(H_V),		_OP(L_y) },
		{ _OP(H_U),		_OP(L_x) },
		{ _OP(H_U),		_OP(L_dq) },
		{ _OP(H_B),	_OP(L_y) },
		{ _OP(H_E),	_OP(L_d) },
		{ _OP(H_L),	_OP(L_x) },
		{ _OP(H_M),		NULL },


		{ _REG_AL,		NULL },
		{ _REG_RAX,		NULL },
		{ _REG_EAX,		NULL },
		{ _REG_DX,		NULL },
		{ _REG_CL,		NULL },
		{ _REG_RDX,	NULL },

		{ _OP(HL_Rd),	_OP(HL_Mb) },
		{ _OP(HL_Rd),	_OP(HL_Mw) },
		{ _OP(HL_Ry),	_OP(HL_Mw) },
		{ _OP(HL_Ry),	_OP(HL_Mb) },
		{ _OP(HL_Ux),		_OP(HL_Md) },
		{ _OP(HL_Ux),		_OP(HL_Mq) },
		{ _OP(HL_Ux),		_OP(HL_Mw) },
		{ _OP(HL_Udq),_OP(HL_Md) },

		{ _OP(Grp_1),		NULL }

	};
	const ZeroOperand Opcode_Prefixs[] =
	{
		{ Inst_prefix_address_size }, // 67h			0	G4
		{ Inst_prefix_lock }, // f0h					1	G1
		{ Inst_prefix_operand_size }, // 66h			2	G3
		{ Inst_prefix_repne_xacquire }, // f2h		3	G1
		{ Inst_prefix_reprepe_xrelease }, // f3h		4	G1
		{ Inst_prefix_seg_cs }, // 2eh				5	G2下面都是
		{ Inst_prefix_seg_ds }, // 3eh				6
		{ Inst_prefix_seg_es }, // 26h				7
		{ Inst_prefix_seg_fs }, // 64h				8
		{ Inst_prefix_seg_gs }, // 65h				9
		{ Inst_prefix_seg_ss }, // 36h				10
	};
	const ZeroOperand Opcode_0[] =
	{
		{ Inst_daa,0,S_i64 },
		{ Inst_aaa,0,S_i64 },
		{ Inst_pusha,1,S_i64 },
		{ Inst_popa,1,S_i64 },
		{ Inst_nop },
		// 5
		{ Inst_ret,0,S_f64 },
		{ Inst_xlat,1 },
		{ Inst_hlt },
		{ Inst_cmc },
		// 9
		{ Inst_das,0,S_i64 },
		{ Inst_aas,0,S_i64 },
		{ Inst_cbw,2 },
		{ Inst_cwd,2 },
		// 13
		{ Inst_fwait,1 },
		{ Inst_sahf },
		{ Inst_lahf },
		// 16
		{ Inst_leave,0,S_d64 },
		{ Inst_ret },
		{ Inst_int_3 },
		{ Inst_into,0,S_i64 },
		{ Inst_iret,0,S_None,(Size_D | Size_Q) },
		// 21
		{ Inst_clc },
		{ Inst_stc },
		{ Inst_cli },
		{ Inst_sti },
		{ Inst_cld },
		{ Inst_std },
		// 27
		{ Inst_syscall,0,S_o64 },
		{ Inst_clts },
		{ Inst_sysret,0,S_o64 },
		// 30
		{ Inst_wrmsr },
		{ Inst_rdtsc },
		{ Inst_rdmsr },
		{ Inst_rdpmc },
		{ Inst_sysenter },
		{ Inst_sysexit },
		{ Inst_getsec },
		// 37
		{ Inst_emms }, // 1, 
		{ Inst_vzeroall,0,S_v },
		// 39
		{ Inst_invd },
		{ Inst_wbinvd },
		// 41
		{ Inst_cpuid },
		{ Inst_rsm }

	};

	const OneOperand Opcode_0_Grp[] =
	{
		{ Inst_null }, // inc dec

	};
	const  OneOperand Opcode_1[] =
	{
		{ Inst_push,	S_i64,			OP_Seg_es },
		{ Inst_pop,		S_i64,			OP_Seg_es },
		{ Inst_push,	S_i64,			OP_Seg_ss },
		{ Inst_pop,		S_i64,			OP_Seg_ss },
		// 4
		{ Inst_inc,		S_i64_o64,	OP_EAX_Rex },
		{ Inst_inc,		S_i64_o64,	OP_ECX_Rex_B },
		{ Inst_inc,		S_i64_o64,	OP_EDX_Rex_X },
		{ Inst_inc,		S_i64_o64,	OP_EBX_Rex_XB },
		{ Inst_inc,		S_i64_o64,	OP_ESP_Rex_R },
		{ Inst_inc,		S_i64_o64,	OP_EBP_Rex_RB },
		{ Inst_inc,		S_i64_o64,	OP_ESI_Rex_RX },
		{ Inst_inc,		S_i64_o64,	OP_EDI_Rex_RXB },
		// 12
		{ Inst_push,	S_d64,			OP_RAX_R8 },
		{ Inst_push,	S_d64,			OP_RCX_R9 },
		{ Inst_push,	S_d64,			OP_RDX_R10 },
		{ Inst_push,	S_d64,			OP_RBX_R11 },
		{ Inst_push,	S_d64,			OP_RSP_R12 },
		{ Inst_push,	S_d64,			OP_RBP_R13 },
		{ Inst_push,	S_d64,			OP_RSI_R14 },
		{ Inst_push,	S_d64,			OP_RDI_R15 },
		// 20
		{ Inst_jo,		S_f64,			OP_Jb },
		{ Inst_jno,		S_f64,			OP_Jb },
		{ Inst_jb,		S_f64,			OP_Jb,		2 },
		{ Inst_jnb,		S_f64,			OP_Jb,		2 },
		{ Inst_jz,		S_f64,			OP_Jb,		1 },
		{ Inst_jnz,		S_f64,			OP_Jb,		1 },
		{ Inst_jbe,		S_f64,			OP_Jb,		1 },
		{ Inst_ja,		S_f64,			OP_Jb,		1 },
		// 28
		{ Inst_ret,		S_f64,			OP_Iw },

		{ Inst_aam,		S_i64,			OP_Ib },
		{ Inst_aad,		S_i64,			OP_Ib },

		{ Inst_loopne,	S_f64,			OP_Jb,		1 },
		{ Inst_loope,	S_f64,			OP_Jb,		1 },
		// 33
		{ Inst_loop,	S_f64,			OP_Jb },
		{ Inst_jrcxz,	S_f64,			OP_Jb },
		// 35
		{ Inst_push,	S_i64,			OP_Seg_cs },
		{ Inst_push,	S_i64,			OP_Seg_ds },
		{ Inst_pop,		S_i64,			OP_Seg_ds },
		// 38
		{ Inst_dec,		S_i64_o64,	OP_EAX_Rex_W },
		{ Inst_dec,		S_i64_o64,	OP_ECX_Rex_WB },
		{ Inst_dec,		S_i64_o64,	OP_EDX_Rex_WX },
		{ Inst_dec,		S_i64_o64,	OP_EBX_Rex_WXB },
		{ Inst_dec,		S_i64_o64,	OP_ESP_Rex_WR },
		{ Inst_dec,		S_i64_o64,	OP_EBP_Rex_WRB },
		{ Inst_dec,		S_i64_o64,	OP_ESI_Rex_WRX },
		{ Inst_dec,		S_i64_o64,	OP_EDI_Rex_WRXB },
		// 46
		{ Inst_pop,		S_d64,			OP_RAX_R8 },
		{ Inst_pop,		S_d64,			OP_RCX_R9 },
		{ Inst_pop,		S_d64,			OP_RDX_R10 },
		{ Inst_pop,		S_d64,			OP_RBX_R11 },
		{ Inst_pop,		S_d64,			OP_RSP_R12 },
		{ Inst_pop,		S_d64,			OP_RBP_R13 },
		{ Inst_pop,		S_d64,			OP_RSI_R14 },
		{ Inst_pop,		S_d64,			OP_RDI_R15 },
		// 54
		{ Inst_push,	S_d64,			OP_Iz },
		{ Inst_push,	S_d64,			OP_Ib },
		// 56
		{ Inst_js,		S_f64,			OP_Jb },
		{ Inst_jns,		S_f64,			OP_Jb },
		{ Inst_jp,		S_f64,			OP_Jb,		1 },
		{ Inst_jnp,		S_f64,			OP_Jb,		2 },
		{ Inst_jl,		S_f64,			OP_Jb,		1 },
		{ Inst_jnl,		S_f64,			OP_Jb,		1 },
		{ Inst_jle,		S_f64,			OP_Jb,		1 },
		{ Inst_jg,		S_f64,			OP_Jb,		1 },
		// 64
		{ Inst_call,	S_i64,			OP_Ap },
		{ Inst_pushf,	S_d64,			OP_Fv,		0,		(Size_D | Size_Q) },
		{ Inst_popf,	S_d64,			OP_Fv,		0,		(Size_D | Size_Q) },
		// 67
		{ Inst_ret,		S_None,			OP_Iw },
		{ Inst_int,		S_None,			OP_Ib },
		// 69
		{ Inst_call,	S_f64,			OP_Jz },
		{ Inst_jmp,		S_f64,			OP_Jz },
		{ Inst_jmp,		S_i64,			OP_Ap },
		{ Inst_jmp,		S_f64,			OP_Jb },
		// 73
		{ Inst_prefetchw,S_None,		OP_Ev },
		// 74 0fh 80-f7
		{ Inst_jo,		S_f64,			OP_Jz },
		{ Inst_jno,		S_f64,			OP_Jz },
		{ Inst_jb,		S_f64,			OP_Jz,		1 },
		{ Inst_jnb,		S_f64,			OP_Jz,		2 },
		{ Inst_jz,		S_f64,			OP_Jz,		1 },
		{ Inst_jnz,		S_f64,			OP_Jz,		1 },
		{ Inst_jbe,		S_f64,			OP_Jz,		1 },
		{ Inst_ja,		S_f64,			OP_Jz,		1 },
			// 82
		{ Inst_seto,	S_None,			OP_Eb },
		{ Inst_setno,	S_None,			OP_Eb },
		{ Inst_setb,	S_None,			OP_Eb,		1 },
		{ Inst_setae,	S_None,			OP_Eb,		2 },
		{ Inst_sete,	S_None,			OP_Eb,		1 },
		{ Inst_setne,	S_None,			OP_Eb,		1 },
		{ Inst_setbe,	S_None,			OP_Eb,		1 },
		{ Inst_seta,	S_None,			OP_Eb,		1 },
			// 90
		{ Inst_push,	S_d64,			OP_Seg_fs },
		{ Inst_pop,		S_d64,			OP_Seg_fs },
			// 92
		{ Inst_js,		S_f64,			OP_Jz },
		{ Inst_jns,		S_f64,			OP_Jz },
		{ Inst_jp,		S_f64,			OP_Jz,		1 },
		{ Inst_jnp,		S_f64,			OP_Jz,		2 },
		{ Inst_jl,		S_f64,			OP_Jz,		1 },
		{ Inst_jnl,		S_f64,			OP_Jz,		1 },
		{ Inst_jle,		S_f64,			OP_Jz,		1 },
		{ Inst_jg,		S_f64,			OP_Jz,		1 },
			// 100
		{ Inst_sets,	S_None,			OP_Eb },
		{ Inst_setns,	S_None,			OP_Eb },
		{ Inst_setp,	S_None,			OP_Eb,		1 },
		{ Inst_setnp,	S_None,			OP_Eb,		1 },
		{ Inst_setl,	S_None,			OP_Eb,		1 },
		{ Inst_setge,	S_None,			OP_Eb,		1 },
		{ Inst_setle,	S_None,			OP_Eb,		1 },
		{ Inst_setg,	S_None,			OP_Eb,		1 },
			// 108
		{ Inst_push,	S_d64,			OP_Seg_gs },
		{ Inst_pop,		S_d64,			OP_Seg_gs },
			// 110
		{ Inst_bswap,	S_None,			OP_RAX_EAX,	0,		Size_None,		OP_R8_R8D },
		{ Inst_bswap,	S_None,			OP_RCX_ECX,	0,		Size_None,		OP_R9_R9D },
		{ Inst_bswap,	S_None,			OP_RDX_EDX,	0,		Size_None,		OP_R10_R10D },
		{ Inst_bswap,	S_None,			OP_RBX_EBX,	0,		Size_None,		OP_R11_R11D },
		{ Inst_bswap,	S_None,			OP_RSP_ESP,	0,		Size_None,		OP_R12_R12D },
		{ Inst_bswap,	S_None,			OP_RBP_EBP,	0,		Size_None,		OP_R13_R13D },
		{ Inst_bswap,	S_None,			OP_RSI_ESI,	0,		Size_None,		OP_R14_R14D },
		{ Inst_bswap,	S_None,			OP_RDI_EDI,	0,		Size_None,		OP_R15_R15D },
			// 118

	};

	const  OneOperand Opcode_1_Grp[] =
	{
		{ Inst_null,		S_None, OP_Eb }, // grp3
		{ Inst_null,		S_None,	OP_Ev }, // grp3
		{ Inst_pop,			S_d64,	OP_Ev }, // grp1A 18

	};
	const  TwoOperands Opcode_2[] =
	{
		/*0*/{ Inst_add,			OP_Eb,			OP_Gb },
		/*1*/{ Inst_add,			OP_Ev,			OP_Gv },
		/*2*/{ Inst_add,			OP_Gb,			OP_Eb },
		/*3*/{ Inst_add,			OP_Gv,			OP_Ev },
		/*4*/{ Inst_add,			OP_AL,			OP_Lb },
		/*5*/{ Inst_add,			OP_RAX,			OP_Iz },
		/*6*/{ Inst_adc,			OP_Eb,			OP_Gb },
		/*7*/{ Inst_adc,			OP_Ev,			OP_Gv },
		/*8*/{ Inst_adc,			OP_Gb,			OP_Eb },
		/*9*/{ Inst_adc,			OP_Gv,			OP_Ev },
		/*10*/{ Inst_adc,			OP_AL,			OP_Lb },
		/*11*/{ Inst_adc,			OP_RAX,			OP_Iz },
		/*12*/{ Inst_and,			OP_Eb,			OP_Gb },
		/*13*/{ Inst_and,			OP_Ev,			OP_Gv },
		/*14*/{ Inst_and,			OP_Gb,			OP_Eb },
		/*15*/{ Inst_and,			OP_Gv,			OP_Ev },
		/*16*/{ Inst_and,			OP_AL,			OP_Lb },
		/*17*/{ Inst_and,			OP_RAX,			OP_Iz },
		/*18*/{ Inst_xor,			OP_Eb,			OP_Gb },
		/*19*/{ Inst_xor,			OP_Ev,			OP_Gv },
		/*20*/{ Inst_xor,			OP_Gb,			OP_Eb },
		/*21*/{ Inst_xor,			OP_Gv,			OP_Ev },
		/*22*/{ Inst_xor,			OP_AL,			OP_Lb },
		/*23*/{ Inst_xor,			OP_RAX,			OP_Iz },
		/*24*/{ Inst_bound,		OP_Gv,			OP_Ma,C_None,S_i64 },
		/*25*/{ Inst_arpl,		OP_Ew,			OP_Gw,C_None,S_i64 },
		/*26*/{ Inst_movsxd,		OP_Gv,			OP_Ev,C_None,S_o64 },
		/*27*/{ Inst_test,		OP_Eb,			OP_Gb },
		/*28*/{ Inst_test,		OP_Ev,			OP_Gv },
		/*29*/{ Inst_xchg,		OP_Eb,			OP_Gb },
		/*30*/{ Inst_xchg,		OP_Ev,			OP_Gv },
		/*31*/{ Inst_xchg,		OP_RAX,			OP_RAX_R8 }, // 与32位nop共用							
		/*32*/{ Inst_xchg,		OP_RAX,			OP_RCX_R9 },
		/*33*/{ Inst_xchg,		OP_RAX,			OP_RDX_R10 },
		/*34*/{ Inst_xchg,		OP_RAX,			OP_RBX_R11 },
		/*35*/{ Inst_xchg,		OP_RAX,			OP_RSP_R12 },
		/*36*/{ Inst_xchg,		OP_RAX,			OP_RBP_R13 },
		/*37*/{ Inst_xchg,		OP_RAX,			OP_RSI_R14 },
		/*38*/{ Inst_xchg,		OP_RAX,			OP_RDI_R15 },
		/*39*/{ Inst_mov,			OP_AL,			OP_Ob },
		/*40*/{ Inst_mov,			OP_RAX,			OP_Ov },
		/*41*/{ Inst_mov,			OP_Ob,			OP_AL },
		/*42*/{ Inst_mov,			OP_Ov,			OP_RAX },
		/*43*/{ Inst_movs,		OP_Yb,			OP_Xb,		C_None,		S_None,		Size_B },
		/*44*/{ Inst_movs,		OP_Yv,			OP_Xv,		C_None,		S_None,		(Size_W | Size_D | Size_Q) },
		/*45*/{ Inst_cmps,		OP_Yb,			OP_Xb,		C_None,		S_None,		Size_B },
		/*46*/{ Inst_cmps,		OP_Yv,			OP_Xv,		C_None,		S_None,		(Size_W | Size_D | Size_Q) },
		/*47*/{ Inst_mov,			OP_AL_R8L ,		OP_Ib },
		/*48*/{ Inst_mov,			OP_CL_R9L ,		OP_Ib },
		/*49*/{ Inst_mov,			OP_DL_R10L,		OP_Ib },
		/*50*/{ Inst_mov,			OP_BL_R11L,		OP_Ib },
		/*51*/{ Inst_mov,			OP_AH_R12L,		OP_Ib },
		/*52*/{ Inst_mov,			OP_CH_R13L,		OP_Ib },
		/*53*/{ Inst_mov,			OP_DH_R14L,		OP_Ib },
		/*54*/{ Inst_mov,			OP_BH_R15L,		OP_Ib },
		/*55*/{ Inst_les,			OP_Gz,			OP_Mp,		C_None,		S_i64 },
		/*56*/{ Inst_lds,			OP_Gz,			OP_Mp,		C_None,		S_i64 },
		/*57*/{ Inst_in,			OP_AL,			OP_Ib },
		/*58*/{ Inst_in,			OP_EAX,			OP_Ib },
		/*59*/{ Inst_out,			OP_Ib,			OP_AL },
		/*60*/{ Inst_out,			OP_Ib,			OP_EAX },
		/*61*/{ Inst_or,			OP_Eb,			OP_Gb },
		/*62*/{ Inst_or,			OP_Ev,			OP_Gv },
		/*63*/{ Inst_or,			OP_Gb,			OP_Eb },
		/*64*/{ Inst_or,			OP_Gv,			OP_Ev },
		/*65*/{ Inst_or,			OP_AL,			OP_Lb },
		/*66*/{ Inst_or,			OP_RAX,			OP_Iz },
		/*67*/{ Inst_sbb,			OP_Eb,			OP_Gb },
		/*68*/{ Inst_sbb,			OP_Ev,			OP_Gv },
		/*69*/{ Inst_sbb,			OP_Gb,			OP_Eb },
		/*70*/{ Inst_sbb,			OP_Gv,			OP_Ev },
		/*71*/{ Inst_sbb,			OP_AL,			OP_Lb },
		/*72*/{ Inst_sbb,			OP_RAX,			OP_Iz },
		/*73*/{ Inst_sub,			OP_Eb,			OP_Gb },
		/*74*/{ Inst_sub,			OP_Ev,			OP_Gv },
		/*75*/{ Inst_sub,			OP_Gb,			OP_Eb },
		/*76*/{ Inst_sub,			OP_Gv,			OP_Ev },
		/*77*/{ Inst_sub,			OP_AL,			OP_Lb },
		/*78*/{ Inst_sub,			OP_RAX,			OP_Iz },
		/*79*/{ Inst_cmp,			OP_Eb,			OP_Gb },
		/*80*/{ Inst_cmp,			OP_Ev,			OP_Gv },
		/*81*/{ Inst_cmp,			OP_Gb,			OP_Eb },
		/*82*/{ Inst_cmp,			OP_Gv,			OP_Ev },
		/*83*/{ Inst_cmp,			OP_AL,			OP_Lb },
		/*84*/{ Inst_cmp,			OP_RAX,			OP_Iz },
		/*85*/{ Inst_ins,			OP_Yb,			OP_DX,		C_None,		S_None,		Size_B },
		/*86*/{ Inst_ins,			OP_Yz,			OP_DX,		C_None,		S_None,		(Size_W | Size_D) },
		/*87*/{ Inst_outs,		OP_DX,			OP_Xb,		C_None,		S_None,		Size_B },
		/*88*/{ Inst_outs,		OP_DX,			OP_Xz,		C_None,		S_None,		(Size_W | Size_D) },
		/*89*/{ Inst_mov,			OP_Eb,			OP_Gb },
		/*90*/{ Inst_mov,			OP_Ev,			OP_Gv },
		/*91*/{ Inst_mov,			OP_Gb,			OP_Eb },
		/*92*/{ Inst_mov,			OP_Gv,			OP_Ev },
		/*93*/{ Inst_mov,			OP_Ev,			OP_Sw },
		/*94*/{ Inst_lea,			OP_Gv,			OP_M },
		/*95*/{ Inst_mov,			OP_Sw,			OP_Ew },
		/*96*/{ Inst_test,		OP_AL,			OP_Ib },
		/*97*/{ Inst_test,		OP_RAX,			OP_Iz },
		/*98*/{ Inst_stos,		OP_Yb,			OP_AL,		C_None,		S_None,		Size_B },
		/*99*/{ Inst_stos,		OP_Yv,			OP_RAX,		C_None,		S_None,		(Size_Q | Size_W | Size_D) },
		/*100*/{ Inst_lods,		OP_AL,			OP_Xb,		C_None,		S_None,		Size_B },
		/*101*/{ Inst_lods,		OP_RAX,			OP_Xv,		C_None,		S_None,		(Size_Q | Size_W | Size_D) },
		/*102*/{ Inst_scas,		OP_AL,			OP_Yb,		C_None,		S_None,		Size_B },
		/*103*/{ Inst_scas,		OP_RAX,			OP_Yv,		C_None,		S_None,		(Size_Q | Size_W | Size_D) },
		/*104*/{ Inst_mov,			OP_RAX_R8 ,		OP_Iv },
		/*105*/{ Inst_mov,			OP_RCX_R9 ,		OP_Iv },
		/*106*/{ Inst_mov,			OP_RDX_R10,		OP_Iv },
		/*107*/{ Inst_mov,			OP_RBX_R11,		OP_Iv },
		/*108*/{ Inst_mov,			OP_RSP_R12,		OP_Iv },
		/*109*/{ Inst_mov,			OP_RBP_R13,		OP_Iv },
		/*110*/{ Inst_mov,			OP_RSI_R14,		OP_Iv },
		/*111*/{ Inst_mov,			OP_RDI_R15,		OP_Iv },
		/*112*/{ Inst_enter,		OP_Iw,			OP_Ib },
		/*113*/{ Inst_in,			OP_AL,			OP_DX },
		/*114*/{ Inst_in,			OP_EAX,			OP_DX },
		/*115*/{ Inst_out,			OP_DX,			OP_AL },
		/*116*/{ Inst_out,			OP_DX,			OP_EAX },
		/*117*/{ Inst_lar,			OP_Gv,			OP_Ew },
		/*118*/{ Inst_lsl,			OP_Gv,			OP_Ew },
		/*119*/{ Inst_vmovups,		OP_Vps,			OP_Wps },
		/*120*/{ Inst_vmovupd,		OP_Vpd,			OP_Wpd,		C_66 },
		/*121*/{ Inst_vmovups,		OP_Wps,			OP_Vps },
		/*122*/{ Inst_vmovupd,		OP_Wpd,			OP_Vpd,		C_66 },
		/*123*/{ Inst_vmovsldup,	OP_Vx,			OP_Wx,		C_F3 },
		/*124*/{ Inst_vmovddup,	OP_Vx,			OP_Wx,		C_F2 },
		/*125*/{ Inst_vmovlps,		OP_Mq,			OP_Vq },
		/*126*/{ Inst_vmovlpd,		OP_Mq,			OP_Vq,		C_66 },
		/*127*/{ Inst_vmovshdup,	OP_Vx,			OP_Wx,		C_F3 },
		/*128*/{ Inst_vmovhps,		OP_Mq,			OP_Vq,		C_None,		S_v1 },
		/*129*/{ Inst_vmovhpd,		OP_Mq,			OP_Vq,		C_66,		S_v1 },
		/*130*/{ Inst_mov,			OP_Rd,			OP_Cd },
		/*131*/{ Inst_mov,			OP_Rd,			OP_Dd },
		/*132*/{ Inst_mov,			OP_Cd,			OP_Rd },
		/*133*/{ Inst_mov,			OP_Dd,			OP_Rd },
		/*134*/{ Inst_vmovmskps,	OP_Gy,			OP_Ups },
		/*135*/{ Inst_vmovmskpd,	OP_Gy,			OP_Upd,		C_66 },
		/*136*/{ Inst_vsqrtps,		OP_Vps,			OP_Wps },
		/*137*/{ Inst_vsqrtpd,		OP_Vpd,			OP_Wpd,		C_66 },
		/*138*/{ Inst_vrsqrtps,	OP_Vps,			OP_Wps },
		/*139*/{ Inst_vrcpps,		OP_Vps,			OP_Wps },
		/*140*/{ Inst_punpcklbw,	OP_Pq,			OP_Qd },
		/*141*/{ Inst_punpcklwd,	OP_Pq,			OP_Qd },
		/*142*/{ Inst_punpckldq,	OP_Pq,			OP_Qd },
		/*143*/{ Inst_packsswb,	OP_Pq,			OP_Qq },
		/*144*/{ Inst_pcmpgtb,		OP_Pq,			OP_Qq },
		/*145*/{ Inst_pcmpgtw,		OP_Pq,			OP_Qq },
		/*146*/{ Inst_pcmpgtd,		OP_Pq,			OP_Qq },
		/*147*/{ Inst_packuswb,	OP_Pq,			OP_Qq },

		/*148*/{ Inst_pcmpeqb,		OP_Pq,			OP_Qq },
		/*149*/{ Inst_pcmpeqw,		OP_Pq,			OP_Qq },
		/*150*/{ Inst_pcmpeqd,		OP_Pq,			OP_Qq },

		/*151*/{ Inst_vmovaps,		OP_Vps,			OP_Wps },
		/*152*/{ Inst_vmovapd,		OP_Vpd,			OP_Wpd,		C_66 },
		/*153*/{ Inst_vmovaps,		OP_Wps,			OP_Vps },
		/*154*/{ Inst_vmovapd,		OP_Wpd,			OP_Vpd,		C_66 },

		/*155*/{ Inst_cvtpi2ps,	OP_Vps,			OP_Qpi },
		/*156*/{ Inst_cvtpi2pd,	OP_Vpd,			OP_Qpi,		C_66 },

		/*157*/{ Inst_vmovntps,	OP_Mps,			OP_Vps },
		/*158*/{ Inst_vmovntpd,	OP_Mpd,			OP_Vpd,		C_66 },

		/*159*/{ Inst_cvttps2pi,	OP_Ppi,			OP_Wps },
		/*160*/{ Inst_cvttpd2pi,	OP_Ppi,			OP_Wpd,		C_66 },
		/*161*/{ Inst_vcvttss2si,	OP_Gy,			OP_Wss,		C_F3 },
		/*162*/{ Inst_vcvttsd2si,	OP_Gy,			OP_Wsd,		C_F2 },

		/*163*/{ Inst_cvtps2pi,	OP_Ppi,			OP_Wps },
		/*164*/{ Inst_cvtpd2pi,	OP_Qpi,			OP_Wpd,		C_66 },
		/*165*/{ Inst_vcvtss2si,	OP_Gy,			OP_Wss,		C_F3 },
		/*166*/{ Inst_vcvtsd2si,	OP_Gy,			OP_Wsd,		C_F2 },

		/*167*/{ Inst_vucomiss,	OP_Vss,			OP_Wss },
		/*168*/{ Inst_vucomisd,	OP_Vsd,			OP_Wsd,		C_66 },
		/*169*/{ Inst_vcomiss,		OP_Vss,			OP_Wss },
		/*170*/{ Inst_vcomisd,		OP_Vsd,			OP_Wsd,		C_66 },

		/*171*/{ Inst_vcvtps2pd,	OP_Vpd,			OP_Wps },
		/*172*/{ Inst_vcvtpd2ps,	OP_Vps,			OP_Wpd,		C_66 },

		/*173*/{ Inst_vcvtdq2ps,	OP_Vps,			OP_Wdq },
		/*174*/{ Inst_vcvtps2dq,	OP_Vdq,			OP_Wps,		C_66 },
		/*175*/{ Inst_vcvttps2dq,	OP_Vdq,			OP_Wps,		C_F3 },

		/*176*/{ Inst_punpckhbw,	OP_Pq,			OP_Qd },
		/*177*/{ Inst_punpckhwd,	OP_Pq,			OP_Qd },
		/*178*/{ Inst_punpckhdq,	OP_Pq,			OP_Qd },
		/*179*/{ Inst_packssdw,	OP_Pq,			OP_Qd },

		/*180*/{ Inst_movd,		OP_Pd,			OP_Ey,		C_None,		S_None,		Size_Q },
		/*181*/{ Inst_vmovd,		OP_Vy,			OP_Ey,		C_66,		S_None,		Size_Q },

		/*182*/{ Inst_movq,		OP_Pq,			OP_Qq },
		/*183*/{ Inst_vmovdqa,		OP_Vx,			OP_Wx,		C_66 },
		/*184*/{ Inst_vmovdqu,		OP_Vx,			OP_Wx,		C_F3 },

		/*185*/{ Inst_vmread,		OP_Ey,			OP_Gy },
		/*186*/{ Inst_vmwrite,		OP_Gy,			OP_Ey },

		/*187*/{ Inst_movd,		OP_Ey,			OP_Pd,		C_None,		S_None,		Size_Q },
		/*188*/{ Inst_vmovd,		OP_Ey,			OP_Vy,		C_66,		S_None,		Size_Q },
		/*189*/{ Inst_vmovq,		OP_Vq,			OP_Wq,		C_F3 },

		/*190*/{ Inst_movq,		OP_Qq,			OP_Pq },
		/*191*/{ Inst_vmovdqa,		OP_Wx,			OP_Vx,		C_66 },
		/*192*/{ Inst_vmovdqu,		OP_Wx,			OP_Vx,		C_F3 },

		// 0f 80-f7h
		/*193*/{ Inst_bt,			OP_Ev,			OP_Gv },

		/*194*/{ Inst_cmpxchg,		OP_Eb,			OP_Gb },
		/*195*/{ Inst_cmpxchg,		OP_Ev,			OP_Gv },

		/*196*/{ Inst_lss,			OP_Gv,			OP_Mp },
		/*197*/{ Inst_btr,			OP_Ev,			OP_Gv },
		/*198*/{ Inst_lfs,			OP_Gv,			OP_Mp },
		/*199*/{ Inst_lgs,			OP_Gv,			OP_Mp },
		/*200*/{ Inst_movzx,		OP_Gv,			OP_Eb },
		/*201*/{ Inst_movzx,		OP_Gv,			OP_Ew },

		/*202*/{ Inst_xadd,		OP_Eb,			OP_Gb },
		/*203*/{ Inst_xadd,		OP_Ev,			OP_Gv },

		/*204*/{ Inst_movnti,		OP_My,			OP_Gy },

		/*205*/{ Inst_psrlw,		OP_Pq,			OP_Qq },
		/*206*/{ Inst_psrld,		OP_Pq,			OP_Qq },
		/*207*/{ Inst_psrlq,		OP_Pq,			OP_Qq },
		/*208*/{ Inst_paddq,		OP_Pq,			OP_Qq },
		/*209*/{ Inst_pmullw,		OP_Pq,			OP_Qq },

		/*210*/{ Inst_vmovq,		OP_Wq,			OP_Vq,		C_66 },
		/*211*/{ Inst_movq2dq,		OP_Vqq,			OP_Nq,		C_F3 },
		/*212*/{ Inst_movdq2q,		OP_Pq,			OP_Uq,		C_F2 },

		/*213*/{ Inst_pmovmskb,	OP_Gd,			OP_Nq },
		/*214*/{ Inst_vpmovmskb,	OP_Gd,			OP_Ux,		C_66 },

		/*215*/{ Inst_pavgb,		OP_Pq,			OP_Qq },
		/*216*/{ Inst_psraw,		OP_Pq,			OP_Qq },
		/*217*/{ Inst_psrad,		OP_Pq,			OP_Qq },
		/*218*/{ Inst_pavgw,		OP_Pq,			OP_Qq },
		/*219*/{ Inst_pmulhuw,		OP_Pq,			OP_Qq },
		/*220*/{ Inst_pmulhw,		OP_Pq,			OP_Qq },

		/*221*/{ Inst_vcvttpd2dq,	OP_Vx,			OP_Wpd,		C_66 },
		/*222*/{ Inst_vcvtdq2pd,	OP_Vx,			OP_Wpd,		C_F3 },
		/*223*/{ Inst_vcvtpd2dq,	OP_Vx,			OP_Wpd,		C_F2 },

		/*224*/{ Inst_movntq,		OP_Mq,			OP_Pq },
		/*225*/{ Inst_vmovntdq,	OP_Mx,			OP_Vx,		C_66 },

		/*226*/{ Inst_vlddqu,		OP_Vx,			OP_Mx,		C_F2 },

		/*227*/{ Inst_psllw,		OP_Pq,			OP_Qq },
		/*228*/{ Inst_pslld,		OP_Pq,			OP_Qq },
		/*229*/{ Inst_psllq,		OP_Pq,			OP_Qq },
		/*230*/{ Inst_pmuludq,		OP_Pq,			OP_Qq },
		/*231*/{ Inst_pmaddwd,		OP_Pq,			OP_Qq },
		/*232*/{ Inst_psadbw,		OP_Pq,			OP_Qq },
		/*233*/{ Inst_maskmovq,	OP_Pq,			OP_Nq },
		/*234*/{ Inst_vmaskmovdqu,	OP_Vdq,			OP_Udq,		C_66 },

		/*235*/{ Inst_bts,			OP_Ev,			OP_Gv },
		/*236*/{ Inst_imul,		OP_Ev,			OP_Gv },

		/*237*/{ Inst_popcnt,		OP_Gv,			OP_Ev,		C_F3 },
		/*238*/{ Inst_btc,			OP_Ev,			OP_Gv },

		/*239*/{ Inst_bsf,			OP_Gv,			OP_Ev },
		/*240*/{ Inst_tzcnt,		OP_Gv,			OP_Ev,		C_F3 },
		/*241*/{ Inst_bsr,			OP_Gv,			OP_Ev },
		/*242*/{ Inst_lzcnt,		OP_Gv,			OP_Ev,		C_F3 },
		/*243*/{ Inst_movsx,		OP_Gv,			OP_Eb },
		/*244*/{ Inst_movsx,		OP_Gv,			OP_Ew },

		/*245*/{ Inst_psubusb,		OP_Pq,			OP_Qq },
		/*246*/{ Inst_psubusw,		OP_Pq,			OP_Qq },
		/*247*/{ Inst_pminub,		OP_Pq,			OP_Qq },
		/*248*/{ Inst_pand,		OP_Pq,			OP_Qq },
		/*249*/{ Inst_paddusb,		OP_Pq,			OP_Qq },
		/*250*/{ Inst_paddusw,		OP_Pq,			OP_Qq },
		/*251*/{ Inst_pmaxub,		OP_Pq,			OP_Qq },
		/*252*/{ Inst_pandn,		OP_Pq,			OP_Qq },

		/*253*/{ Inst_psubsb,		OP_Pq,			OP_Qq },
		/*254*/{ Inst_psubsw,		OP_Pq,			OP_Qq },
		/*255*/{ Inst_pminsw,		OP_Pq,			OP_Qq },
		/*256*/{ Inst_por,			OP_Pq,			OP_Qq },
		/*257*/{ Inst_paddsb,		OP_Pq,			OP_Qq },
		/*258*/{ Inst_paddsw,		OP_Pq,			OP_Qq },
		/*259*/{ Inst_pmaxsw,		OP_Pq,			OP_Qq },
		/*260*/{ Inst_pxor,		OP_Pq,			OP_Qq },

		/*261*/{ Inst_psubb,		OP_Pq,			OP_Qq },
		/*262*/{ Inst_psubw,		OP_Pq,			OP_Qq },
		/*263*/{ Inst_psubd,		OP_Pq,			OP_Qq },
		/*264*/{ Inst_psubq,		OP_Pq,			OP_Qq },
		/*265*/{ Inst_paddb,		OP_Pq,			OP_Qq },
		/*266*/{ Inst_paddw,		OP_Pq,			OP_Qq },
		/*267*/{ Inst_paddd,		OP_Pq,			OP_Qq },
		/*268*/{ Inst_pshufb,		OP_Pq,			OP_Qq },
		/*269*/{ Inst_phaddw,		OP_Pq,			OP_Qq },
		/*270*/{ Inst_phaddd,		OP_Pq,			OP_Qq },
		/*271*/{ Inst_phaddsw,		OP_Pq,			OP_Qq },
		/*272*/{ Inst_pmaddubsw,	OP_Pq,			OP_Qq },
		/*273*/{ Inst_phsubw,		OP_Pq,			OP_Qq },
		/*274*/{ Inst_phsubd,		OP_Pq,			OP_Qq },
		/*275*/{ Inst_phsubsw,		OP_Pq,			OP_Qq },
		/*276*/{ Inst_pblendvb,	OP_Vdq,			OP_Wdq,		C_66 },
		/*277*/{ Inst_vpmovsxbw,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*278*/{ Inst_vpmovzxbw,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*279*/{ Inst_vpmovsxbd,	OP_Vx,		OP_Ux_Md,C_66 },
		/*280*/{ Inst_vpmovzxbd,	OP_Vx,		OP_Ux_Md,C_66 },
		/*281*/{ Inst_vphminposuw,	OP_Vdq,		OP_Wdq,C_66 },
		/*282*/{ Inst_vpmovsxbq,	OP_Vx,		OP_Ux_Mw,C_66 },
		/*283*/{ Inst_vpmovzxbq,	OP_Vx,		OP_Ux_Mw,C_66 },
		/*284*/{ Inst_vpmovsxwd,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*285*/{ Inst_vpmovzxwd,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*286*/{ Inst_blendvps,	OP_Vdq,		OP_Wdq,C_66 },
		/*287*/{ Inst_vpmovsxwq,	OP_Vx,		OP_Ux_Md,C_66 },
		/*288*/{ Inst_vpmovzxwq,	OP_Vx,		OP_Ux_Md,C_66 },
		/*289*/{ Inst_blendvpd,	OP_Vdq,		OP_Wdq,C_66 },
		/*290*/{ Inst_vpmovsxdq,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*291*/{ Inst_vpmovzxdq,	OP_Vx,		OP_Ux_Mq,C_66 },
		/*292*/{ Inst_vptest,		OP_Vx,		OP_Wx,C_66 },
		/*293*/{ Inst_invept,		OP_Gy,		OP_Mdq,C_66 },
		/*294*/{ Inst_invvpid,		OP_Gy,		OP_Mdq,C_66 },
		/*295*/{ Inst_invpcid,		OP_Gy,		OP_Mdq,C_66 },
		/*296*/{ Inst_movbe,		OP_Gy,		OP_My },
		/*297*/{ Inst_movbe,		OP_Gw,		OP_Mw,C_66 },
		/*298*/{ Inst_crc32,		OP_Gd,		OP_Eb,C_F2 },
		/*299*/{ Inst_crc32,		OP_Gd,		OP_Eb,C_66_And_F2 },
		/*300*/{ Inst_movbe,		OP_My,		OP_Gy },
		/*301*/{ Inst_movbe,		OP_Mw,		OP_Gw,C_66 },
		/*302*/{ Inst_crc32,		OP_Gd,		OP_Ey,C_F2 },
		/*303*/{ Inst_crc32,		OP_Gd,		OP_Ew,C_66_And_F2 },
		/*304*/{ Inst_adcx,		OP_Gy,		OP_Ey,C_66 },
		/*305*/{ Inst_adox,		OP_Gy,		OP_Ey,C_F3 },
		/*306*/{ Inst_psignb,		OP_Pq,		OP_Qq },
		/*307*/{ Inst_psignw,		OP_Pq,		OP_Qq },
		/*308*/{ Inst_psignd,		OP_Pq,		OP_Qq },
		/*309*/{ Inst_pmulhrsw,	OP_Pq,		OP_Qq },
		/*310*/{ Inst_vtestps,		OP_Vx,		OP_Wx,C_66,S_v },
		/*311*/{ Inst_vtestpd,		OP_Vx,		OP_Wx,C_66,S_v },
		/*312*/{ Inst_vbroadcastss,OP_Vx,		OP_Wd,C_66,S_v },
		/*313*/{ Inst_vbroadcastsd,OP_Vqq,		OP_Wq,C_66,S_v },
		/*314*/{ Inst_vbroadcastf128,OP_Vqq,		OP_Mdq,C_66,S_v },
		/*315*/{ Inst_pabsb,		OP_Pq,		OP_Qq },
		/*316*/{ Inst_vpabsb,		OP_Vx,		OP_Wx,C_66 },
		/*317*/{ Inst_pabsw,		OP_Pq,		OP_Qq },
		/*318*/{ Inst_vpabsw,		OP_Vx,		OP_Wx,C_66 },
		/*319*/{ Inst_pabsd,		OP_Pq,		OP_Qq },
		/*320*/{ Inst_vpabsd,		OP_Vx,		OP_Wx,C_66 },
		/*321*/{ Inst_vmovntdqa,	OP_Vx,		OP_Mx,C_66 },
		/*322*/{ Inst_vpbroadcastd,OP_Vx,		OP_Wx,C_66,S_v },
		/*323*/{ Inst_vpbroadcastq,OP_Vx,		OP_Wx,C_66,S_v },
		/*324*/{ Inst_vbroadcasti128,OP_Vqq,		OP_Mdq,C_66,S_v },
		/*325*/{ Inst_vpbroadcastb,OP_Vx,		OP_Wx,C_66,S_v },
		/*326*/{ Inst_vpbroadcastw,OP_Vx,		OP_Wx,C_66,S_v },
		/*327*/{ Inst_vaesimc,		OP_Vdq,		OP_Wdq,C_66 },
		/*328*/{ Inst_cmovo,		OP_Gv,		OP_Ev },
		/*329*/{ Inst_cmovno,		OP_Gv,		OP_Ev },
		/*330*/{ Inst_cmovb,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,2 },
		/*331*/{ Inst_cmovae,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,2 },
		/*332*/{ Inst_cmove,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*333*/{ Inst_cmovne,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*334*/{ Inst_cmovbe,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*335*/{ Inst_cmova,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*336*/{ Inst_cmovs,		OP_Gv,		OP_Ev },
		/*337*/{ Inst_cmovns,		OP_Gv,		OP_Ev },
		/*338*/{ Inst_cmovp,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*339*/{ Inst_cmovnp,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*340*/{ Inst_cmovl,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*341*/{ Inst_cmovnl,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*342*/{ Inst_cmovle,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },
		/*343*/{ Inst_cmovnle,		OP_Gv,		OP_Ev,C_None,S_None,Size_None,1 },


	};
	const  TwoOperands Opcode_2_Grp[] =
	{

		{ Inst_null,			OP_Eb,		OP_Ib }, // grp1 grp2 grp11
		{ Inst_null,			OP_Ev,		OP_Iz }, // grp1 grp11
		{ Inst_null,			OP_Eb,		OP_Ib,C_None,S_i64 }, // grp1
		{ Inst_null,			OP_Ev,		OP_Ib }, // grp1 grp2
													 // 4
		{ Inst_null,			OP_Eb,		OP_1 }, // grp2
		{ Inst_null,			OP_Ev,		OP_1 }, // grp2
		{ Inst_null,			OP_Eb,		OP_CL }, // grp2
		{ Inst_null,			OP_Ev,		OP_CL }, // grp2


	};
	const  ThreeOperands Opcode_3[] =
	{
		/*0*/{ Inst_imul,C_None,OP_Gv,OP_Ev,OP_Iz },
		/*1*/{ Inst_imul,C_None,OP_Gv,OP_Ev,OP_Ib },
		/*2*/{ Inst_vmovss,C_F3,OP_Vx,OP_Hx,OP_Wss },
		/*3*/{ Inst_vmovsd,C_F2,OP_Vx,OP_Hx,OP_Wsd },
		/*4*/{ Inst_vmovss,C_F3,OP_Wss,OP_Hx,OP_Vss },
		/*5*/{ Inst_vmovsd,C_F2,OP_Wsd,OP_Hx,OP_Vsd },
		/*6*/{ Inst_vmovlps,C_None,OP_Vq,OP_Hq,OP_Mq },
		/*7*/{ Inst_vmovhlps,C_None,OP_Vq,OP_Hq,OP_Uq },
		/*8*/{ Inst_vmovlpd,C_66,OP_Vq,OP_Hq,OP_Mq },
		/*9*/{ Inst_vunpcklps,C_None,OP_Vx,OP_Hx,OP_Wx },
		/*10*/{ Inst_vunpcklpd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*11*/{ Inst_vunpckhps,C_None,OP_Vx,OP_Hx,OP_Wx },
		/*12*/{ Inst_vunpckhpd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*13*/{ Inst_vmovhps,C_None,OP_Vdq,OP_Hq,OP_Mq,S_v1 },
		/*14*/{ Inst_vmovlhps,C_None,OP_Vdq,OP_Hq,OP_Uq },
		/*15*/{ Inst_vmovhpd,C_66,OP_Vdq,OP_Hq,OP_Mq,S_v1 },
		/*16*/{ Inst_vsqrtss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*17*/{ Inst_vsqrtsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },
		/*18*/{ Inst_vrsqrtss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*19*/{ Inst_vrcpss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*20*/{ Inst_vandps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*21*/{ Inst_vandpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*22*/{ Inst_vandnps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*23*/{ Inst_vandnpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*24*/{ Inst_vorps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*25*/{ Inst_vorpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*26*/{ Inst_vxorps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*27*/{ Inst_vxorpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*28*/{ Inst_vpunpcklbw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*29*/{ Inst_vpunpcklwd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*30*/{ Inst_vpunpckldq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*31*/{ Inst_vpacksswb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*32*/{ Inst_vpcmpgtb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*33*/{ Inst_vpcmpgtw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*34*/{ Inst_vpcmpgtd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*35*/{ Inst_vpackuswb,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*36*/{ Inst_pshufw,C_None,OP_Pq,OP_Qq,OP_Ib },
		/*37*/{ Inst_vpshufd,C_66,OP_Vx,OP_Wx,OP_Ib },
		/*38*/{ Inst_vpshufhw,C_F3,OP_Vx,OP_Wx,OP_Ib },
		/*39*/{ Inst_vpshuflw,C_F2,OP_Vx,OP_Wx,OP_Ib },

		/*40*/{ Inst_vpcmpeqb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*41*/{ Inst_vpcmpeqw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*42*/{ Inst_vpcmpeqd,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*43*/{ Inst_vcvtsi2ss,C_F3,OP_Vss,OP_Hss,OP_Ey },
		/*44*/{ Inst_vcvtsi2sd,C_F2,OP_Vsd,OP_Hsd,OP_Ey },

		/*45*/{ Inst_vaddps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*46*/{ Inst_vaddpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*47*/{ Inst_vaddss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*48*/{ Inst_vaddsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*49*/{ Inst_vmulps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*50*/{ Inst_vmulpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*51*/{ Inst_vmulps,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*52*/{ Inst_vmulpd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*53*/{ Inst_vcvtss2sd,C_F3,OP_Vsd,OP_Hx,OP_Wss },
		/*54*/{ Inst_vcvtsd2ss,C_F2,OP_Vss,OP_Hx,OP_Wsd },

		/*55*/{ Inst_vsubps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*56*/{ Inst_vsubpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },

		/*57*/{ Inst_vsubss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*58*/{ Inst_vsubsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*59*/{ Inst_vminps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*60*/{ Inst_vminpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*61*/{ Inst_vminss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*62*/{ Inst_vminsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*63*/{ Inst_vdivps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*64*/{ Inst_vdivpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*65*/{ Inst_vdivss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*66*/{ Inst_vdivsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*67*/{ Inst_vmaxps,C_None,OP_Vps,OP_Hps,OP_Wps },
		/*68*/{ Inst_vmaxpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*69*/{ Inst_vmaxss,C_F3,OP_Vss,OP_Hss,OP_Wss },
		/*70*/{ Inst_vmaxsd,C_F2,OP_Vsd,OP_Hsd,OP_Wsd },

		/*71*/{ Inst_vpunpckhbw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*72*/{ Inst_vpunpckhwd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*73*/{ Inst_vpunpckhdq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*74*/{ Inst_vpackssdw,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*75*/{ Inst_vpunpcklqdq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*76*/{ Inst_vpunpckhqdq,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*77*/{ Inst_vhaddpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*78*/{ Inst_vhaddps,C_F2,OP_Vps,OP_Hps,OP_Wps },
		/*79*/{ Inst_vhsubpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*80*/{ Inst_vhsubps,C_F2,OP_Vps,OP_Hps,OP_Wps },
		// 0f 80-f7h
		/*81*/{ Inst_shld,C_None,OP_Ev,OP_Gv,OP_Ib },
		/*82*/{ Inst_shld,C_None,OP_Ev,OP_Gv,OP_CL },

		/*83*/{ Inst_pinsrw,C_None,OP_Pq,OP_Ry_Mw,OP_Ib },

		/*84*/{ Inst_pextrw,C_None,OP_Gd,OP_Nq,OP_Ib },
		/*85*/{ Inst_vpextrw,C_66,OP_Gd,OP_Udq,OP_Ib },

		/*86*/{ Inst_vaddsubpd,C_66,OP_Vpd,OP_Hpd,OP_Wpd },
		/*87*/{ Inst_vaddsubps,C_F2,OP_Vps,OP_Hps,OP_Wps },

		/*88*/{ Inst_vpsrlw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*89*/{ Inst_vpsrld,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*90*/{ Inst_vpsrlq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*91*/{ Inst_vpaddq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*92*/{ Inst_vpmullw,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*93*/{ Inst_vpavgb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*94*/{ Inst_vpsraw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*95*/{ Inst_vpsrad,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*96*/{ Inst_vpavgw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*97*/{ Inst_vpmulhuw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*98*/{ Inst_vpmulhw,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*99*/{ Inst_vpsllw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*100*/{ Inst_vpslld,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*101*/{ Inst_vpsllq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*102*/{ Inst_vpmuludq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*103*/{ Inst_vpmaddwd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*104*/{ Inst_vpsadbw,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*105*/{ Inst_shrd,C_None,OP_Ev,OP_Gv,OP_Ib },
		/*106*/{ Inst_shrd,C_None,OP_Ev,OP_Gv,OP_CL },

		/*107*/{ Inst_vpsubusb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*108*/{ Inst_vpsubusw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*109*/{ Inst_vpminub,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*110*/{ Inst_vpand,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*111*/{ Inst_vpaddusb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*112*/{ Inst_vpaddusw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*113*/{ Inst_vpmaxub,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*114*/{ Inst_vpandn,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*115*/{ Inst_vpsubsb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*116*/{ Inst_vpsubsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*117*/{ Inst_vpminsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*118*/{ Inst_vpor,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*119*/{ Inst_vpaddsb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*120*/{ Inst_vpaddsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*121*/{ Inst_vpmaxsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*122*/{ Inst_vpxor,C_66,OP_Vx,OP_Hx,OP_Wx },

		/*123*/{ Inst_vpsubb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*124*/{ Inst_vpsubw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*125*/{ Inst_vpsubd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*126*/{ Inst_vpsubq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*127*/{ Inst_vpaddb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*128*/{ Inst_vpaddw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*129*/{ Inst_vpaddd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*130*/{ Inst_vpshufb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*131*/{ Inst_vphaddw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*132*/{ Inst_vphaddd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*133*/{ Inst_vphaddsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*134*/{ Inst_vpmaddubsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*135*/{ Inst_vphsubw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*136*/{ Inst_vphsubd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*137*/{ Inst_vphsubsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*138*/{ Inst_vcvtph2ps,C_66,OP_Vx,OP_Wx,OP_Ib,S_v },
		/*139*/{ Inst_vpermps,C_66,OP_Vqq,OP_Hqq,OP_Wqq,S_v },
		/*140*/{ Inst_vpermd,C_66,OP_Vqq,OP_Hqq,OP_Wqq,S_v },
		/*141*/{ Inst_vpcmpgtq,C_None,OP_Vx,OP_Hx,OP_Wx },
		/*142*/{ Inst_vpmulld,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*143*/{ Inst_vpsrlvd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_Q },
		/*144*/{ Inst_vpsravd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v },
		/*145*/{ Inst_vpsllvd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_Q },
		/*146*/{ Inst_vgatherdd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_Q },
		/*147*/{ Inst_vgatherqd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_Q },
		/*148*/{ Inst_vgatherdps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*149*/{ Inst_vgatherqps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*150*/{ Inst_vfmaddsub132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*151*/{ Inst_vfmsubadd132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*152*/{ Inst_vfmsubadd213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*153*/{ Inst_vfmaddsub213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*154*/{ Inst_vfmaddsub231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*155*/{ Inst_vfmsubadd231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*156*/{ Inst_andn,C_None,OP_Gy,OP_By,OP_Ey,S_v },
		/*157*/{ Inst_bzhi,C_None,OP_Gy,OP_Ey,OP_By,S_v },
		/*158*/{ Inst_pext,C_F3,OP_Gy,OP_By,OP_Ey,S_v },
		/*159*/{ Inst_pdep,C_F2,OP_Gy,OP_By,OP_Ey,S_v },
		/*160*/{ Inst_bextr,C_None,OP_Gy,OP_Ey,OP_By,S_v },
		/*161*/{ Inst_shlx,C_66,OP_Gy,OP_Ey,OP_By,S_v },
		/*162*/{ Inst_sarx,C_F3,OP_Gy,OP_Ey,OP_By,S_v },
		/*163*/{ Inst_shrx,C_F2,OP_Gy,OP_Ey,OP_By,S_v },
		/*164*/{ Inst_vpsignb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*165*/{ Inst_vpsignw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*166*/{ Inst_vpsignd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*167*/{ Inst_vpmulhrsw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*168*/{ Inst_vpermilps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v },
		/*169*/{ Inst_vpermilpd,C_66,OP_Vx,OP_Hx,OP_Wx,S_v },
		/*170*/{ Inst_vpmuldq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*171*/{ Inst_vpcmpeqq,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*172*/{ Inst_vpackusdw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*173*/{ Inst_vmaskmovps,C_66,OP_Vx,OP_Hx,OP_Mx,S_v },
		/*174*/{ Inst_vmaskmovpd,C_66,OP_Vx,OP_Hx,OP_Mx,S_v },
		/*175*/{ Inst_vmaskmovps,C_66,OP_Mx,OP_Hx,OP_Vx,S_v },
		/*176*/{ Inst_vmaskmovpd,C_66,OP_Mx,OP_Hx,OP_Vx,S_v },
		/*177*/{ Inst_vpminsb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*178*/{ Inst_vpminsd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*179*/{ Inst_vpminuw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*180*/{ Inst_vpminud,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*181*/{ Inst_vpmaxsb,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*182*/{ Inst_vpmaxsd,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*183*/{ Inst_vpmaxuw,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*184*/{ Inst_vpmaxud,C_66,OP_Vx,OP_Hx,OP_Wx },
		/*185*/{ Inst_vpmaskmovd,C_66,OP_Vx,OP_Hx,OP_Mx,S_v,Size_Q },
		/*186*/{ Inst_vpmaskmovd,C_66,OP_Mx,OP_Vx,OP_Hx,S_v,Size_Q },
		/*187*/{ Inst_vfmadd132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*188*/{ Inst_vfmadd132ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*189*/{ Inst_vfmsub132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*190*/{ Inst_vfmsub132ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*191*/{ Inst_vfnmadd132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*192*/{ Inst_vfnmadd132ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*193*/{ Inst_vfnmsub132ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*194*/{ Inst_vfnmsub132ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*195*/{ Inst_vfmadd213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*196*/{ Inst_vfmadd213ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*197*/{ Inst_vfmsub213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*198*/{ Inst_vfmsub213ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*199*/{ Inst_vfnmadd213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*200*/{ Inst_vfnmadd213ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*201*/{ Inst_vfnmsub213ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*202*/{ Inst_vfnmsub213ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*203*/{ Inst_vfmadd231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*204*/{ Inst_vfmadd231ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*205*/{ Inst_vfmsub231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*206*/{ Inst_vfmsub231ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*207*/{ Inst_vfnmadd231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*208*/{ Inst_vfnmadd231ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*209*/{ Inst_vfnmsub231ps,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*210*/{ Inst_vfnmsub231ss,C_66,OP_Vx,OP_Hx,OP_Wx,S_v,Size_D },
		/*211*/{ Inst_vaesenc,C_66,OP_Vdq,OP_Hdq,OP_Wdq },
		/*212*/{ Inst_vaesenclast,C_66,OP_Vdq,OP_Hdq,OP_Wdq },
		/*213*/{ Inst_vaesdec,C_66,OP_Vdq,OP_Hdq,OP_Wdq },
		/*214*/{ Inst_vaesdeclast,C_66,OP_Vdq,OP_Hdq,OP_Wdq },
		/*215*/{ Inst_vpermq,C_66,OP_Vqq,OP_Wqq,OP_Ib,S_v },
		/*216*/{ Inst_vpermpd,C_66,OP_Vqq,OP_Wqq,OP_Ib,S_v },
		/*217*/{ Inst_vpermilps,C_66,OP_Vx,OP_Wx,OP_Ib,S_v },
		/*218*/{ Inst_vpermilpd,C_66,OP_Vx,OP_Wx,OP_Ib,S_v },
		/*219*/{ Inst_vpextrb,C_66,OP_Rd_Mb,OP_Vdq,OP_Ib },
		/*220*/{ Inst_vpextrw,C_66,OP_Rd_Mw,OP_Vdq,OP_Ib },
		/*221*/{ Inst_vpextrd,C_66,OP_Ey,OP_Vdq,OP_Ib,S_None,Size_Q },
		/*222*/{ Inst_vextractps,C_66,OP_Ed,OP_Vdq,OP_Ib },
		/*223*/{ Inst_vpcmpestrm,C_66,OP_Vdq,OP_Wdq,OP_Ib },
		/*224*/{ Inst_vpcmpestri,C_66,OP_Vdq,OP_Wdq,OP_Ib },
		/*225*/{ Inst_vpcmpistrm,C_66,OP_Vdq,OP_Wdq,OP_Ib },
		/*226*/{ Inst_vpcmpistri,C_66,OP_Vdq,OP_Wdq,OP_Ib },
		/*227*/{ Inst_rorx,C_F2,OP_Gy,OP_Ey,OP_Ib,S_v },
		/*228*/{ Inst_vroundps,C_66,OP_Vx,OP_Wx,OP_Ib },
		/*229*/{ Inst_vroundpd,C_66,OP_Vx,OP_Wx,OP_Ib },
		/*230*/{ Inst_vroundss,C_66,OP_Vss,OP_Wss,OP_Ib },
		/*231*/{ Inst_vroundsd,C_66,OP_Vsd,OP_Wsd,OP_Ib },
		/*232*/{ Inst_palignr,C_None,OP_Pq,OP_Qq,OP_Ib },
		/*233*/{ Inst_vextractf128,C_66,OP_Wdq,OP_Vqq,OP_Ib,S_v },
		/*234*/{ Inst_vcvtps2ph,C_66,OP_Wx,OP_Vx,OP_Ib,S_v },
		/*235*/{ Inst_vextracti128,C_66,OP_Wdq,OP_Vqq,OP_Ib,S_v },
		/*236*/{ Inst_vaeskeygen,C_66,OP_Vdq,OP_Wdq,OP_Ib }


	};
	const  FourOperands Opcode_4[] =
	{
		{ Inst_vcmpps,		C_None,		OP_Vps,	OP_Hps,	OP_Wps,	OP_Ib },
		{ Inst_vcmppd,		C_66,		OP_Vpd,	OP_Hpd,	OP_Wps,	OP_Ib },
		{ Inst_vcmpss,		C_F3,		OP_Vss,	OP_Hss,	OP_Wss,	OP_Ib },
		{ Inst_vcmpsd,		C_F2,		OP_Vsd,	OP_Hsd,	OP_Wsd,	OP_Ib },
		// 4

		{ Inst_vpinsrw,		C_66,		OP_Vdq,	OP_Hdq,	OP_Ry_Mw,	OP_Ib },
		// 5
		{ Inst_vshufps,		C_None,		OP_Vps,	OP_Hps,	OP_Wps,	OP_Ib },
		{ Inst_vshufpd,		C_66,		OP_Vpd,	OP_Hpd,	OP_Wpd,	OP_Ib },
		// 7
		{ Inst_mulx,		C_F2,		OP_By,	OP_Gy,	OP_RDX,		OP_Ey,	S_v },

		{ Inst_vpblendd,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib,	S_v },

		{ Inst_vperm2f128,	C_66,		OP_Vqq,	OP_Hqq,	OP_Wqq,	OP_Ib },

		{ Inst_vpinsrb,		C_66,		OP_Vdq,	OP_Hdq,	OP_Ry_Mb,	OP_Ib },

		{ Inst_vinsertps,	C_66,		OP_Vdq,	OP_Hdq,	OP_Udq_Md,	OP_Ib },

		{ Inst_vpinsrd,		C_66,		OP_Vdq,	OP_Hdq,	OP_Ey,	OP_Ib,	S_None,	Size_Q },

		{ Inst_vdpps,		C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },
		{ Inst_vdppd,		C_66,		OP_Vdq,	OP_Hdq,	OP_Wdq,	OP_Ib },
		{ Inst_vmpsadbw,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },
		{ Inst_vpclmulqdq,	C_66,		OP_Vdq,	OP_Hdq,	OP_Wdq,	OP_Ib },
		{ Inst_vperm2i128,	C_66,		OP_Vqq,	OP_Hqq,	OP_Wqq,	OP_Ib,	S_v },

		{ Inst_vblendps,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },
		{ Inst_vblendpd,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },
		{ Inst_vpblendw,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },
		{ Inst_vpalignr,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Ib },

		{ Inst_vinsertf128,	C_66,		OP_Vqq,	OP_Hqq,	OP_Wqq,	OP_Ib,	S_v },
		{ Inst_vinserti128,	C_66,		OP_Vqq,	OP_Hqq,	OP_Wqq,	OP_Ib,	S_v },

		{ Inst_vblendvps,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Lx,	S_v },
		{ Inst_vblendvpd,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Lx,	S_v },
		{ Inst_vpblendvb,	C_66,		OP_Vx,	OP_Hx,	OP_Wx,	OP_Lx,	S_v },

	};
}

