#pragma once
#include <Windows.h>
enum class DllCharacteristics:WORD
{
	HighEntropyVa = IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA,
	DynamicBase = IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE,
	ForceIntegrity = IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY,
	NxCompat = IMAGE_DLLCHARACTERISTICS_NX_COMPAT,
	NoIsolation = IMAGE_DLLCHARACTERISTICS_NO_ISOLATION,
	NoSeh = IMAGE_DLLCHARACTERISTICS_NO_SEH,
	NoBind = IMAGE_DLLCHARACTERISTICS_NO_BIND,
	Appcontainer = IMAGE_DLLCHARACTERISTICS_APPCONTAINER,
	WdmDriver = IMAGE_DLLCHARACTERISTICS_WDM_DRIVER,
	GuardCf = IMAGE_DLLCHARACTERISTICS_GUARD_CF,
	TerminalServerAware = IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE,
};