#pragma once
#include <Windows.h>
enum class SubsystemType :WORD
{
	Unknown = IMAGE_SUBSYSTEM_UNKNOWN,
	Native = IMAGE_SUBSYSTEM_NATIVE,
	WindowsGui = IMAGE_SUBSYSTEM_WINDOWS_GUI,
	WindowsCui = IMAGE_SUBSYSTEM_WINDOWS_CUI,
	Os2Cui = IMAGE_SUBSYSTEM_OS2_CUI,
	PosixCui = IMAGE_SUBSYSTEM_POSIX_CUI,
	NativeWindows = IMAGE_SUBSYSTEM_NATIVE_WINDOWS,
	WindowsCeGui = IMAGE_SUBSYSTEM_WINDOWS_CE_GUI,
	EfiApplication = IMAGE_SUBSYSTEM_EFI_APPLICATION,
	EfiBootServiceDriver = IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER,
	EfiRuntimeDriver = IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER,
	EfiRom = IMAGE_SUBSYSTEM_EFI_ROM,
	Xbox = IMAGE_SUBSYSTEM_XBOX,
	WindowsBootApplication = IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION,
};