#pragma once
// 存储指令对应的字符串，使用枚举值做下标
#include <Windows.h>
#include <WinBase.h>
namespace Asm
{
#pragma region 指令们
	extern const PCSTR InstructionNames[];

	enum InstructionIndexs
	{
		Inst_null,
		Inst_aaa,
		Inst_aad,
		Inst_aam,
		Inst_aas,
		Inst_adc,
		Inst_adcx,
		Inst_add,
		Inst_adox,
		Inst_and,
		Inst_andn,
		Inst_arpl,
		Inst_bextr,
		Inst_blendvpd,
		Inst_blendvps,
		Inst_blsi,
		Inst_blsmsk,
		Inst_blsr,
		Inst_bound,
		Inst_bsf,
		Inst_bsr,
		Inst_bswap,
		Inst_bt,
		Inst_btc,
		Inst_btr,
		Inst_bts,
		Inst_bzhi,
		Inst_call,
		Inst_cbw, // 2
		Inst_cwde,
		Inst_cdqe,
		Inst_clac,
		Inst_clc,
		Inst_cld,
		Inst_clflush,
		Inst_cli,
		Inst_clts,
		Inst_cmc,
		Inst_cmova, // 1
		Inst_cmovnbe,
		Inst_cmovae, // 2
		Inst_cmovnb,
		Inst_cmovnc,
		Inst_cmovb, // 2
		Inst_cmovc,
		Inst_cmovnae,
		Inst_cmovbe,// 1
		Inst_cmovna,
		Inst_cmove, // 1
		Inst_cmovz,
		Inst_cmovl, // 1
		Inst_cmovnge,
		Inst_cmovle, // 1
		Inst_cmovng,
		Inst_cmovne, // 1
		Inst_cmovnz,
		Inst_cmovnl, // 1
		Inst_cmovge,
		Inst_cmovnle, // 1
		Inst_cmovg,
		Inst_cmovno,
		Inst_cmovnp, // 1
		Inst_cmovpo,
		Inst_cmovns,
		Inst_cmovo,
		Inst_cmovp, // 1
		Inst_cmovpe,
		Inst_cmovs,
		Inst_cmp,
		Inst_cmps, // b w d
		Inst_cmpxch,
		Inst_cmpxchg,
		Inst_cpuid,
		Inst_crc32,
		Inst_cvtpd2pi,
		Inst_cvtpi2pd,
		Inst_cvtpi2ps,
		Inst_cvtps2pi,
		Inst_cvttpd2pi,
		Inst_cvttps2pi,
		Inst_cwd, // 2
		Inst_cdq,
		Inst_cqo,
		Inst_daa,
		Inst_das,
		Inst_dec,
		Inst_div,
		Inst_emms,
		Inst_enter,
		Inst_esc,
		Inst_fxrstor,
		Inst_fxsave,
		Inst_getsec,
		Inst_hlt,
		Inst_idiv,
		Inst_imul,
		Inst_in,
		Inst_inc,
		Inst_ins, // b w d
		Inst_int,
		Inst_int_3,
		Inst_into,
		Inst_invd,
		Inst_invept,
		Inst_invlpg,
		Inst_invpcid,
		Inst_invvpid,
		Inst_iret, //d q
		Inst_ja, // 1
		Inst_jnbe,
		Inst_jb, // 2
		Inst_jnae,
		Inst_jc,
		Inst_jnz, // 1
		Inst_jne,
		Inst_jbe, // 1
		Inst_jna,
		Inst_jz, // 1
		Inst_je,
		Inst_jg, // 1
		Inst_jnle,
		Inst_jl, // 1
		Inst_jnge,
		Inst_jle, // 1
		Inst_jng,
		Inst_jmp,
		Inst_jmpe,
		Inst_jnb, //2
		Inst_jae,
		Inst_jnc,
		Inst_jnl, // 1
		Inst_jge,
		Inst_jno,
		Inst_jnp, // 1
		Inst_jpo,
		Inst_jns,
		Inst_jo,
		Inst_jp, // 1
		Inst_jpe,
		Inst_jrcxz,
		Inst_js,
		Inst_lahf,
		Inst_lar,
		Inst_ldmxcsr,
		Inst_lds,
		Inst_lea,
		Inst_leave,
		Inst_les,
		Inst_lfence,
		Inst_lfs,
		Inst_lgdt,
		Inst_lgs,
		Inst_lidt,
		Inst_lldt,
		Inst_lmsw,
		Inst_lods, // b w d q
		Inst_loop,
		Inst_loope, // 1
		Inst_loopz,
		Inst_loopne, // 1
		Inst_loopnz,
		Inst_lsl,
		Inst_lss,
		Inst_ltr,
		Inst_lzcnt,
		Inst_maskmovq,
		Inst_mfence,
		Inst_monitor,
		Inst_mov,
		Inst_movd,
		Inst_movq,
		Inst_movbe,
		Inst_movdq2q,
		Inst_movnti,
		Inst_movntq,
		Inst_movq2dq,
		Inst_movs, // b w d q
		Inst_movsx,
		Inst_movsxd,
		Inst_movw,
		Inst_movzx,
		Inst_mul,
		Inst_mulx,
		Inst_mwait,
		Inst_neg,
		Inst_nop,
		Inst_not,
		Inst_or,
		Inst_out,
		Inst_outs, // b w d
		Inst_pabsb,
		Inst_pabsd,
		Inst_pabsw,
		Inst_packssdw,
		Inst_packsswb,
		Inst_packuswb,
		Inst_paddb,
		Inst_paddd,
		Inst_paddq,
		Inst_paddsb,
		Inst_paddsw,
		Inst_paddusb,
		Inst_paddusw,
		Inst_paddw,
		Inst_palignr,
		Inst_pand,
		Inst_pandn,
		Inst_pause,
		Inst_pavgb,
		Inst_pavgw,
		Inst_pblendvb,
		Inst_pcmpeqb,
		Inst_pcmpeqd,
		Inst_pcmpeqw,
		Inst_pcmpgtb,
		Inst_pcmpgtd,
		Inst_pcmpgtw,
		Inst_pdep,
		Inst_pext,
		Inst_pextrw,
		Inst_phaddd,
		Inst_phaddsw,
		Inst_phaddw,
		Inst_phsubd,
		Inst_phsubsw,
		Inst_phsubw,
		Inst_pinsrw,
		Inst_pmaddubsw,
		Inst_pmaddwd,
		Inst_pmaxsw,
		Inst_pmaxub,
		Inst_pminsw,
		Inst_pminub,
		Inst_pmovmskb,
		Inst_pmulhrsw,
		Inst_pmulhuw,
		Inst_pmulhw,
		Inst_pmullw,
		Inst_pmuludq,
		Inst_pop,
		Inst_popa, // 1
		Inst_popad,
		Inst_popf, // d q(64)
		Inst_popcnt,
		Inst_por,
		Inst_prefetch_nta,
		Inst_prefetch_t0,
		Inst_prefetch_t1,
		Inst_prefetch_t2,
		Inst_prefetchw,
		Inst_prefix_address_size, // 67h
		Inst_prefix_lock, // f0h
		Inst_prefix_operand_size, // 66h
		Inst_prefix_repne_xacquire, // f2h
		Inst_prefix_reprepe_xrelease, // f3h
		Inst_prefix_seg_cs, // 2eh
		Inst_prefix_seg_ds, // 3eh
		Inst_prefix_seg_es, // 26h
		Inst_prefix_seg_fs, // 64h
		Inst_prefix_seg_gs, // 65h
		Inst_prefix_seg_ss, // 36h
		Inst_psadbw,
		Inst_pshufb,
		Inst_pshufw,
		Inst_psignb,
		Inst_psignd,
		Inst_psignw,
		Inst_pslld,
		Inst_psllq,
		Inst_psllw,
		Inst_psrad,
		Inst_psraw,
		Inst_psrld,
		Inst_psrlq,
		Inst_psrlw,
		Inst_psubb,
		Inst_psubd,
		Inst_psubq,
		Inst_psubsb,
		Inst_psubsw,
		Inst_psubusb,
		Inst_psubusw,
		Inst_psubw,
		Inst_punpckhbw,
		Inst_punpckhdq,
		Inst_punpckhwd,
		Inst_punpcklbw,
		Inst_punpckldq,
		Inst_punpcklwd,
		Inst_push,
		Inst_pusha, // 1
		Inst_pushad,
		Inst_pushf, // d q(64)
		Inst_pxor,
		Inst_rcl,
		Inst_rcr,
		Inst_rdfsbase,
		Inst_rdgsbase,
		Inst_rdmsr,
		Inst_rdpmc,
		Inst_rdrand,
		Inst_rdseed,
		Inst_rdtsc,
		Inst_rdtscp,
		Inst_ret,
		Inst_rol,
		Inst_ror,
		Inst_rorx,
		Inst_rsm,
		Inst_sahf,
		Inst_sar,
		Inst_sarx,
		Inst_sbb,
		Inst_scas, // bwdq
		Inst_seta, // 1
		Inst_setnbe,
		Inst_setae, // 2
		Inst_setnb,
		Inst_setnc,
		Inst_setb, // 2
		Inst_setc,
		Inst_setnae,
		Inst_setbe, // 1
		Inst_setna,
		Inst_sete, // 1
		Inst_setz,
		Inst_setg, // 1
		Inst_setnle,
		Inst_setge, // 1
		Inst_setnl,
		Inst_setl, // 1
		Inst_setnge,
		Inst_setle, // 1
		Inst_setng,
		Inst_setne, // 1
		Inst_setnz,
		Inst_setno,
		Inst_setnp, // 1
		Inst_setpo,
		Inst_setns,
		Inst_seto,
		Inst_setp, // 1
		Inst_setpe,
		Inst_sets,
		Inst_sfence,
		Inst_sgdt,
		Inst_shl,
		Inst_sal,
		Inst_shld,
		Inst_shlx,
		Inst_shr,
		Inst_shrd,
		Inst_shrx,
		Inst_sidt,
		Inst_sldt,
		Inst_smsw,
		Inst_stac,
		Inst_stc,
		Inst_std,
		Inst_sti,
		Inst_stmxcsr,
		Inst_stos, // b w d q
		Inst_str,
		Inst_sub,
		Inst_swapgs,
		Inst_syscall,
		Inst_sysenter,
		Inst_sysexit,
		Inst_sysret,
		Inst_test,
		Inst_tzcnt,
		Inst_ud2,
		Inst_vaddpd,
		Inst_vaddps,
		Inst_vaddsd,
		Inst_vaddss,
		Inst_vaddsubpd,
		Inst_vaddsubps,
		Inst_vaesdec,
		Inst_vaesdeclast,
		Inst_vaesenc,
		Inst_vaesenclast,
		Inst_vaesimc,
		Inst_vaeskeygen,
		Inst_vandnpd,
		Inst_vandnps,
		Inst_vandpd,
		Inst_vandps,
		Inst_vblendpd,
		Inst_vblendps,
		Inst_vblendvpd,
		Inst_vblendvps,
		Inst_vbroadcastf128,
		Inst_vbroadcasti128,
		Inst_vbroadcastsd,
		Inst_vbroadcastss,
		Inst_vcmppd,
		Inst_vcmpps,
		Inst_vcmpsd,
		Inst_vcmpss,
		Inst_vcomisd,
		Inst_vcomiss,
		Inst_vcvtdq2pd,
		Inst_vcvtdq2ps,
		Inst_vcvtpd2dq,
		Inst_vcvtpd2ps,
		Inst_vcvtph2ps,
		Inst_vcvtps2dq,
		Inst_vcvtps2pd,
		Inst_vcvtps2ph,
		Inst_vcvtsd2si,
		Inst_vcvtsd2ss,
		Inst_vcvtsi2sd,
		Inst_vcvtsi2ss,
		Inst_vcvtss2sd,
		Inst_vcvtss2si,
		Inst_vcvttpd2dq,
		Inst_vcvttps2dq,
		Inst_vcvttsd2si,
		Inst_vcvttss2si,
		Inst_vdivpd,
		Inst_vdivps,
		Inst_vdivsd,
		Inst_vdivss,
		Inst_vdppd,
		Inst_vdpps,
		Inst_verr,
		Inst_verw,
		Inst_vextractf128,
		Inst_vextracti128,
		Inst_vextractps,
		Inst_vfmadd132ps, // d
		Inst_vfmadd132ss, // d
		Inst_vfmadd213ps, // d
		Inst_vfmadd213ss, // d
		Inst_vfmadd231ps, // d
		Inst_vfmadd231ss, // d
		Inst_vfmaddsub132ps, // d
		Inst_vfmaddsub213ps, // d
		Inst_vfmaddsub231ps, // d
		Inst_vfmsub132ps, // d
		Inst_vfmsub132ss, // d
		Inst_vfmsub213ps,  // d
		Inst_vfmsub213ss, // d
		Inst_vfmsub231ps, // d
		Inst_vfmsub231ss, // d
		Inst_vfmsubadd132ps, // d
		Inst_vfmsubadd213ps, // d
		Inst_vfmsubadd231ps, // d
		Inst_vfnmadd132ps, // d
		Inst_vfnmadd132ss, // d
		Inst_vfnmadd213ps, // d
		Inst_vfnmadd213ss, // d
		Inst_vfnmadd231ps, // d
		Inst_vfnmadd231ss, // d
		Inst_vfnmsub132ps, // d
		Inst_vfnmsub132ss, // d
		Inst_vfnmsub213ps, // d
		Inst_vfnmsub213ss, // d
		Inst_vfnmsub231ps, // d
		Inst_vfnmsub231ss, // d
		Inst_vgatherdd, // q
		Inst_vgatherdps, // d
		Inst_vgatherqd, // q
		Inst_vgatherqps, // d
		Inst_vhaddpd,
		Inst_vhaddps,
		Inst_vhsubpd,
		Inst_vhsubps,
		Inst_vinsertf128,
		Inst_vinserti128,
		Inst_vinsertps,
		Inst_vlddqu,
		Inst_vmaskmovdqu,
		Inst_vmaskmovpd,
		Inst_vmaskmovps,
		Inst_vmaxpd,
		Inst_vmaxps,
		Inst_vmaxsd,
		Inst_vmaxss,
		Inst_vmcall,
		Inst_vmclear,
		Inst_vmfunc,
		Inst_vminpd,
		Inst_vminps,
		Inst_vminsd,
		Inst_vminss,
		Inst_vmlaunch,
		Inst_vmovapd,
		Inst_vmovaps,
		Inst_vmov,
		Inst_vmovddup,
		Inst_vmovdqa,
		Inst_vmovdqu,
		Inst_vmovhlps,
		Inst_vmovhpd,
		Inst_vmovhps,
		Inst_vmovlhps,
		Inst_vmovlpd,
		Inst_vmovlps,
		Inst_vmovmskpd,
		Inst_vmovmskps,
		Inst_vmovntdq,
		Inst_vmovntdqa,
		Inst_vmovntpd,
		Inst_vmovntps,
		Inst_vmovd,
		Inst_vmovq,
		Inst_vmovsd,
		Inst_vmovshdup,
		Inst_vmovsldup,
		Inst_vmovss,
		Inst_vmovupd,
		Inst_vmovups,
		Inst_vmpsadbw,
		Inst_vmptrld,
		Inst_vmptrst,
		Inst_vmread,
		Inst_vmresume,
		Inst_vmulpd,
		Inst_vmulps,
		Inst_vmulsd,
		Inst_vmulss,
		Inst_vmwrite,
		Inst_vmxoff,
		Inst_vmxon,
		Inst_vorpd,
		Inst_vorps,
		Inst_vpabsb,
		Inst_vpabsd,
		Inst_vpabsw,
		Inst_vpackssdw,
		Inst_vpacksswb,
		Inst_vpackusdw,
		Inst_vpackuswb,
		Inst_vpaddb,
		Inst_vpaddd,
		Inst_vpaddq,
		Inst_vpaddsb,
		Inst_vpaddsw,
		Inst_vpaddusb,
		Inst_vpaddusw,
		Inst_vpaddw,
		Inst_vpalignr,
		Inst_vpand,
		Inst_vpandn,
		Inst_vpavgb,
		Inst_vpavgw,
		Inst_vpblendd,
		Inst_vpblendvb,
		Inst_vpblendw,
		Inst_vpbroadcastb,
		Inst_vpbroadcastd,
		Inst_vpbroadcastq,
		Inst_vpbroadcastw,
		Inst_vpclmulqdq,
		Inst_vpcmpeqb,
		Inst_vpcmpeqd,
		Inst_vpcmpeqq,
		Inst_vpcmpeqw,
		Inst_vpcmpestri,
		Inst_vpcmpestrm,
		Inst_vpcmpgtb,
		Inst_vpcmpgtd,
		Inst_vpcmpgtq,
		Inst_vpcmpgtw,
		Inst_vpcmpistri,
		Inst_vpcmpistrm,
		Inst_vperm2f128,
		Inst_vperm2i128,
		Inst_vpermd,
		Inst_vpermilpd,
		Inst_vpermilps,
		Inst_vpermpd,
		Inst_vpermps,
		Inst_vpermq,
		Inst_vpextrb,
		Inst_vpextrd,
		Inst_vpextrq,
		Inst_vpextrw,
		Inst_vphaddd,
		Inst_vphaddsw,
		Inst_vphaddw,
		Inst_vphminposuw,
		Inst_vphsubd,
		Inst_vphsubsw,
		Inst_vphsubw,
		Inst_vpinsrb,
		Inst_vpinsrd,
		Inst_vpinsrq,
		Inst_vpinsrw,
		Inst_vpmaddubsw,
		Inst_vpmaddwd,
		Inst_vpmaskmovd,
		Inst_vpmaskmovq,
		Inst_vpmaxsb,
		Inst_vpmaxsd,
		Inst_vpmaxsw,
		Inst_vpmaxub,
		Inst_vpmaxud,
		Inst_vpmaxuw,
		Inst_vpminsb,
		Inst_vpminsd,
		Inst_vpminsw,
		Inst_vpminub,
		Inst_vpminud,
		Inst_vpminuw,
		Inst_vpmovmskb,
		Inst_vpmovsxbd,
		Inst_vpmovsxbq,
		Inst_vpmovsxbw,
		Inst_vpmovsxdq,
		Inst_vpmovsxwd,
		Inst_vpmovsxwq,
		Inst_vpmovzxbd,
		Inst_vpmovzxbq,
		Inst_vpmovzxbw,
		Inst_vpmovzxdq,
		Inst_vpmovzxwd,
		Inst_vpmovzxwq,
		Inst_vpmuldq,
		Inst_vpmulhrsw,
		Inst_vpmulhuw,
		Inst_vpmulhw,
		Inst_vpmulld,
		Inst_vpmullw,
		Inst_vpmuludq,
		Inst_vpor,
		Inst_vpsadbw,
		Inst_vpshufb,
		Inst_vpshufd,
		Inst_vpshufhw,
		Inst_vpshuflw,
		Inst_vpsignb,
		Inst_vpsignd,
		Inst_vpsignw,
		Inst_vpslld,
		Inst_vpslldq,
		Inst_vpsllq,
		Inst_vpsllvd, // q
		Inst_vpsllw,
		Inst_vpsrad,
		Inst_vpsravd,
		Inst_vpsraw,
		Inst_vpsrld,
		Inst_vpsrldq,
		Inst_vpsrlq,
		Inst_vpsrlvd, // q
		Inst_vpsrlw,
		Inst_vpsubb,
		Inst_vpsubd,
		Inst_vpsubq,
		Inst_vpsubsb,
		Inst_vpsubsw,
		Inst_vpsubusb,
		Inst_vpsubusw,
		Inst_vpsubw,
		Inst_vptest,
		Inst_vpunpckhbw,
		Inst_vpunpckhdq,
		Inst_vpunpckhqdq,
		Inst_vpunpckhwd,
		Inst_vpunpcklbw,
		Inst_vpunpckldq,
		Inst_vpunpcklqdq,
		Inst_vpunpcklwd,
		Inst_vpxor,
		Inst_vrcpps,
		Inst_vrcpss,
		Inst_vroundpd,
		Inst_vroundps,
		Inst_vroundsd,
		Inst_vroundss,
		Inst_vrsqrtps,
		Inst_vrsqrtss,
		Inst_vshufpd,
		Inst_vshufps,
		Inst_vsqrtpd,
		Inst_vsqrtps,
		Inst_vsqrtsd,
		Inst_vsqrtss,
		Inst_vsubpd,
		Inst_vsubps,
		Inst_vsubsd,
		Inst_vsubss,
		Inst_vtestpd,
		Inst_vtestps,
		Inst_vucomisd,
		Inst_vucomiss,
		Inst_vunpckhpd,
		Inst_vunpckhps,
		Inst_vunpcklpd,
		Inst_vunpcklps,
		Inst_vxorpd,
		Inst_vxorps,
		Inst_vzeroall,
		Inst_wait, // 1
		Inst_fwait,
		Inst_wbinvd,
		Inst_wrfsbase,
		Inst_wrgsbase,
		Inst_wrmsr,
		Inst_xabort,
		Inst_xadd,
		Inst_xbegin,
		Inst_xchg,
		Inst_xend,
		Inst_xgetbv,
		Inst_xlat, // 1
		Inst_xlatb,
		Inst_xor,
		Inst_xrstor,
		Inst_xsave,
		Inst_xsaveopt,
		Inst_xsetbv,
		Inst_xtest,
		InstructionIndexs_end
	};
#pragma endregion
}