#pragma once
#include <Windows.h>
#include <WinBase.h>
#include <intrin.h>
#include <winternl.h>
#include <functional>
#include <algorithm>
#include <mutex>
#include <list>
#include <boost\iterator_adaptors.hpp>
using boost::iterator_facade;
using boost::forward_traversal_tag;
using boost::iterator_core_access;