#pragma once
#include <Windows.h>
#include <WinBase.h>
#include <intrin.h>
#include <winternl.h>
#include <functional>
#include <algorithm>
#include <mutex>
#include <list>
#include <cassert>
#include <atomic>
#include <functional>
#include <iterator>