#pragma once
#include <Windows.h>
#include <WinBase.h>
#include "EnumHexConverter.h"
#include "UITypeEditor.h"
namespace PeImageClr
{
	using namespace System::ComponentModel;

	[FlagsAttribute]
	[EditorAttribute(FlagsEditor<DllCharacteristicsEntries>::typeid, UITypeEditor::typeid)]
	public enum class DllCharacteristicsEntries :WORD
	{
		HIGH_ENTROPY_VA = IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA,
		DYNAMIC_BASE = IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE,
		FORCE_INTEGRITY = IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY,
		NX_COMPAT = IMAGE_DLLCHARACTERISTICS_NX_COMPAT,
		NO_ISOLATION = IMAGE_DLLCHARACTERISTICS_NO_ISOLATION,
		NO_SEH = IMAGE_DLLCHARACTERISTICS_NO_SEH,
		NO_BIND = IMAGE_DLLCHARACTERISTICS_NO_BIND,
		APPCONTAINER = IMAGE_DLLCHARACTERISTICS_APPCONTAINER,
		WDM_DRIVER = IMAGE_DLLCHARACTERISTICS_WDM_DRIVER,
		GUARD_CF = IMAGE_DLLCHARACTERISTICS_GUARD_CF,
		TERMINAL_SERVER_AWARE = IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE
	};
}  // namespace PeImageClr
