#pragma once
#include <Windows.h>
#include <WinBase.h>
#include "EnumHexConverter.h"
namespace PeImageClr
{
	[TypeConverter(EnumHexConverter::typeid)]
	public enum class SubsystemValues :WORD
	{
		UNKNOWN = IMAGE_SUBSYSTEM_UNKNOWN,
		NATIVE = IMAGE_SUBSYSTEM_NATIVE,
		WINDOWS_GUI = IMAGE_SUBSYSTEM_WINDOWS_GUI,
		WINDOWS_CUI = IMAGE_SUBSYSTEM_WINDOWS_CUI,
		OS2_CUI = IMAGE_SUBSYSTEM_OS2_CUI,
		POSIX_CUI = IMAGE_SUBSYSTEM_POSIX_CUI,
		NATIVE_WINDOWS = IMAGE_SUBSYSTEM_NATIVE_WINDOWS,
		WINDOWS_CE_GUI = IMAGE_SUBSYSTEM_WINDOWS_CE_GUI,
		EFI_APPLICATION = IMAGE_SUBSYSTEM_EFI_APPLICATION,
		EFI_BOOT_SERVICE_DRIVER = IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER,
		EFI_RUNTIME_DRIVER = IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER,
		EFI_ROM = IMAGE_SUBSYSTEM_EFI_ROM,
		XBOX = IMAGE_SUBSYSTEM_XBOX,
		WINDOWS_BOOT_APPLICATION = IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION
	};
}  // namespace PeImageClr
